# Generated by Django 6.0 on 2026-01-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='feedback',
            field=models.TextField(blank=True, help_text='Optional feedback about your experience', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rate your experience (1-5 stars)', null=True),
        ),
    ]
