# Generated by Django 6.0 on 2026-01-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contact_created_at_contact_feedback_contact_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Contact message'),
        ),
    ]
