# Generated by Django 6.0 on 2026-01-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_cart_remove_contact_message_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False, help_text='Mark this product as trending to show on home page'),
        ),
    ]
