# Generated by Django 6.0 on 2026-01-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_employee_owner_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profiles/employees/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profiles/owners/'),
        ),
    ]