# Generated by Django 6.0 on 2026-01-22 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_employee_profile_image_owner_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Customer first name', max_length=50)),
                ('last_name', models.CharField(help_text='Customer last name', max_length=50)),
                ('email', models.EmailField(help_text='Customer email', max_length=254)),
                ('phone', models.CharField(help_text='Customer phone number', max_length=15)),
                ('address', models.TextField(help_text='Delivery address')),
                ('city', models.CharField(help_text='City', max_length=50)),
                ('pincode', models.CharField(help_text='Postal code', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Order notes', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total order amount', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Order status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who placed the order (null for guest orders)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per item', max_digits=10)),
                ('quantity', models.IntegerField(help_text='Quantity ordered')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal for this item', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
