# Generated by Django 6.0 on 2026-01-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_order_payment_method'),
    ]

    operations = [
    ]
