# Generated by Django 6.0 on 2026-01-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_product_id_product_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this product is currently active/available'),
        ),
        migrations.AddField(
            model_name='product',
            name='disaction',
            field=models.TextField(blank=True, help_text='Reason or description for deactivation', null=True),
        ),
    ]
