# Generated by Django 4.2.27 on 2026-02-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Slider item title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle or description', max_length=300, null=True)),
                ('image', models.ImageField(help_text='Slider background image', upload_to='slider/')),
                ('button_text', models.CharField(blank=True, help_text='Text for call-to-action button', max_length=50, null=True)),
                ('button_url', models.CharField(blank=True, help_text='URL for button link', max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slider item is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slider Item',
                'verbose_name_plural': 'Slider Items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
