# Generated by Django 4.2.27 on 2026-02-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20260216_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_special',
            field=models.BooleanField(default=False, help_text='Mark this product as special for highlighting'),
        ),
    ]
