from django.urls import path
from . import views
 
urlpatterns = [
     path("", views.home, name="home"),
     path("about/", views.about, name="about"),
     path("product/", views.product, name="product"),
     path("product/<int:id>/", views.view_p, name="view_p"),
     path("product/<int:product_id>/add-review/", views.add_review, name="add_review"),
     path("contact/", views.contact, name="contact"),
     path("cart/", views.cart, name="cart"),
     path("Terms/", views.Terms, name="Terms"),
     path("Privacy/", views.Privacy, name="Privacy" ),
     path("login/", views.user_login, name="login"),
     path("csignup/", views.csignup, name="csignup"),
     path("logout/", views.user_logout, name="logout"),
     path("profile/", views.profile, name="profile"),
     path("order-history/", views.order_history, name="order_history"),
     path("download-bill/<int:order_id>/", views.download_bill, name="download_bill"),
     path("verify/", views.verify, name="verify"),
     path("otp/", views.otp, name="otp"),
     path("payment/", views.payment, name="payment"),
     path("admin/", views.admin_dashboard, name="admin_dashboard"),
     path("admin/add-employee/", views.admin_add_employee, name="admin_add_employee"),
     path("admin/add-product/", views.add_product, name="admin_add_product"),
     path("admin/edit-product/<int:product_id>/", views.edit_product, name="admin_edit_product"),
     path("admin/get-product/<int:product_id>/", views.get_product, name="admin_get_product"),
     path("admin/toggle-product/<int:product_id>/", views.toggle_product_status, name="admin_toggle_product"),
     path("admin/delete-product/<int:product_id>/", views.delete_product, name="admin_delete_product"),
     path("employee/login/", views.employee_login, name="employee_login"),
     path("employee/dashboard/", views.employee_dashboard, name="employee_dashboard"),
     path("employee/update-order/<int:order_id>/", views.update_order_status, name="update_order_status"),
     path("owner/login/", views.owner_login, name="owner_login"),
     path("owner/dashboard/", views.owner_dashboard, name="owner_dashboard"),
     path("owner/update-order/<int:order_id>/", views.owner_update_order_status, name="owner_update_order_status"),
     path("owner/add-product/", views.add_product, name="add_product"),
     path("owner/edit-product/<int:product_id>/", views.edit_product, name="edit_product"),
     path("owner/get-product/<int:product_id>/", views.get_product, name="get_product"),
     path("owner/toggle-product/<int:product_id>/", views.toggle_product_status, name="toggle_product_status"),
     path("owner/delete-product/<int:product_id>/", views.delete_product, name="delete_product"),
     path("owner/get-employee/<int:employee_id>/", views.get_employee, name="get_employee"),
     path("owner/edit-employee/<int:employee_id>/", views.edit_employee, name="edit_employee"),
     path("owner/delete-employee/<int:employee_id>/", views.delete_employee, name="delete_employee"),
     path("owner/add-employee/", views.owner_add_employee, name="owner_add_employee"),
     path("owner/sales-data/", views.sales_data, name="sales_data"),
]